from registers.avarma_registers import (
    AVARMA_BINARY_REGISTERS,
    AVARMA_NUMBER_REGISTERS,
    AVARMA_SENSOR_REGISTERS,
    AVARMA_SWITCH_REGISTERS,
)

regs = (
    AVARMA_NUMBER_REGISTERS
    + AVARMA_SWITCH_REGISTERS
    + AVARMA_BINARY_REGISTERS
    + AVARMA_SENSOR_REGISTERS
)

with open("AVARMA_REGISTERS.md", "w", encoding="UTF-8") as out:
    out.write("# Hofman Energy Avrama Registers\n\n")
    out.write("[//]: # (AUTO GENERATED DO NOT EDIT THIS FILE BY HAND!) \n\n")
    out.write(
        "|Parameter|Register Start Address|Register Offset|Description|Unit|Class|Factor|\n"
    )
    out.write("|---|---|---|---|---|---|---|\n")
    for reg in regs:
        out.write("|")
        out.write(reg.parameter_id)
        out.write("|")
        out.write(f"0x{reg.start_address:04x}")
        out.write("|")
        out.write(f"0x{reg.register_offset:02x}")
        out.write("|")
        out.write(reg.description)
        out.write("|")
        out.write(str(reg.unit_of_measurement))
        out.write("|")
        out.write(str(reg.device_class))
        out.write("|")
        out.write(str(reg.register_factor))
        out.write("|\n")
